print("My Daily Routine")
print("I wake up at 5 AM")
print("I go to school at 7 AM")
print("I play with my friends in the evening")
print("I study for 6 hours at morning")
print("Total study hours in a week:", 6 * 7)